# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-27 07:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FirstServer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=32)),
                ('level', models.IntegerField()),
                ('login_time', models.DateTimeField()),
            ],
        ),
    ]
